export interface EmotionResult {
  emotion: string;
  confidence: number;
  timestamp: number;
}

export interface VideoAnalysisResult {
  emotions: EmotionResult[];
  dominantEmotion: string;
  averageConfidence: number;
  total_detections?: number;
  duration?: number;
  analysis_details?: {
    confidence_level?: string;
    frames_analyzed?: number;
    successful_detections?: number;
    detection_rate?: string;
    [key: string]: any;
  };
  emotion_timeline?: any;
  faces_detected?: number;
  face_quality_score?: number;
  timestamp: number;
}

export interface SentimentResult {
  label: string;
  confidence: number;
  scores: {
    negative: number;
    neutral: number;
    positive: number;
  };
  polarity: number;
  subjectivity: number;
  intensity: string;
}

export interface SpeechAnalysisResult {
  transcribed_text: string;
  sentiment: SentimentResult | { label: string; confidence: number };
  emotions: EmotionResult[];
  genAIInsights?: string | null;
  technicalReport?: string | null;
  audio_duration_seconds: number;
  timestamp: number;
  session_id?: string;
  emoBuddyResponse?: string;
}

export interface ChatMessage {
  id: string;
  text: string;
  timestamp: number;
  analysis: {
    sentiment: {
      label: string;
      score: number;
    };
    emotions: EmotionResult[];
    mentalState: string;
  };
}

export interface SurveyLikertData {
  q1: number; // I feel happy and relaxed while doing my job.
  q2: number; // I frequently feel anxious or stressed because of my work.
  q3: number; // I feel emotionally exhausted at the end of my workday.
  q4: number; // I feel motivated and excited about my work.
  q5: number; // I feel a sense of accomplishment and purpose in my role.
  q6: number; // I find myself feeling detached or indifferent about my work.
  q7: number; // My workload is manageable within my regular working hours.
  q8: number; // I have control over how I organize and complete my tasks.
  q9: number; // My manager and team provide support when I face challenges.
  q10: number; // I feel my personal time and work–life balance are respected by the organization.
}

// API Types
export interface ApiError {
  message: string;
  code?: string;
  details?: unknown;
  statusCode?: number;
  endpoint?: string;
  timestamp?: string;
}

export interface ApiResponse<T> {
  data: T;
  success: boolean;
  message?: string;
  timestamp?: string;
}

// Health Check Types
export interface ServiceStatus {
  status: string;
  latency?: number;
  version?: string;
  lastChecked?: string;
}

export interface HealthCheckResponse {
  status: string;
  version: string;
  timestamp: string;
  uptime?: number;
  services: {
    [key: string]: ServiceStatus;
  };
  system?: {
    memory_mb?: number;
    cpu_percent?: number;
  };
}

export interface MetricsData {
  requestCount: number;
  errorRate: number;
  avgResponseTime: number;
  serviceStatus: {
    [key: string]: boolean;
  };
}

// Form Types
export interface FormField {
  id: string;
  type: 'text' | 'number' | 'slider' | 'radio' | 'checkbox' | 'textarea';
  label: string;
  required: boolean;
  options?: string[];
  min?: number;
  max?: number;
  step?: number;
}

export interface SurveySchema {
  title: string;
  description: string;
  fields: FormField[];
}

export interface BurnoutResult {
  employeeId: string;
  burnRate: number;
  surveyScore: string;
  mentalHealthSummary: string;
  recommendations: {
    title: string;
    description: string;
    icon: string;
  }[];
  riskLevel: 'Low' | 'Medium' | 'High';
  breakdown?: {
    category: string;
    score: number;
    description: string;
  }[];
}

// Authentication Types
export interface User {
  id: string;
  username?: string;
  email: string;
  first_name: string;
  last_name: string;
  phone_number?: string;
  employee_id?: string;
  department_id?: number;
  role: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface UserLogin {
  email: string;
  password: string;
}

export interface UserRegister {
  email: string;
  password: string;
  confirmPassword?: string;
  firstName: string;
  lastName: string;
  phoneNumber: string;
  departmentId: number;
  // employee_id and role are auto-generated by backend
}

export interface TokenResponse {
  access_token: string;
  token_type: string;
  expires_in?: number;
}

export interface Notification {
  id: number;
  message: string;
  type: 'success' | 'error' | 'warning' | 'info';
  timestamp?: number;
}