version: '3.8'

services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules # Exclude node_modules from host bind mount
    command: ["npm", "start"]
    environment:
      REACT_APP_VIDEO_API_URL: http://video-backend:8001
      REACT_APP_STT_API_URL: http://stt-backend:8002
      REACT_APP_CHAT_API_URL: http://chat-backend:8003
      REACT_APP_SURVEY_API_URL: http://survey-backend:8004
      REACT_APP_INTEGRATED_API_URL: http://integrated-backend:9000
    depends_on:
      - video-backend
      - stt-backend
      - chat-backend
      - survey-backend
      - integrated-backend

  video-backend:
    build:
      context: ./services/video/emp_face
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./services/video/emp_face:/app
    environment:
      PYTHONUNBUFFERED: 1
    # command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  stt-backend:
    build:
      context: ./services/stt/api
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./services/stt/api:/app
    environment:
      PYTHONUNBUFFERED: 1
    # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]

  chat-backend:
    build:
      context: ./services/chat/chat/mental_state_analyzer
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - ./services/chat/chat/mental_state_analyzer:/app
    environment:
      PYTHONUNBUFFERED: 1
    # command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8003", "--reload"]

  survey-backend:
    build:
      context: ./services/survey/survey
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    volumes:
      - ./services/survey/survey:/app
    environment:
      PYTHONUNBUFFERED: 1
    # command: ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "8004", "--reload"]

  integrated-backend:
    build:
      context: ./services/integrated/backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./services/integrated/backend:/app
    environment:
      PYTHONUNBUFFERED: 1
    # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000", "--reload"] 